Financial-Times/dotcom-page-kit

packages/dotcom-ui-footer/src/components/partials.tsx
`null © THE FINANCIAL TIMES LTD 2019`
`© THE FINANCIAL TIMES LTD 2019`
`Markets data delayed by at least 15 minutes. © THE FINANCIAL TIMES LTD 2019`
`Markets data delayed by at least 15 minutes. © THE FINANCIAL TIMES LTD 2019`
=> Prevent string of 'null' displayed in legal footer variant

packages/dotcom-server-handlebars/readme.md
Currently these hyperlinks link to 404 pages.
This PR corrects them so they link to the intended pages.
=> Fix dotcom-server-handlebars package README links

packages/dotcom-ui-header/styles.scss
Removes 'top' as a sass option in dotcom-ui-header as it's no longer an option on oHeader https://github.com/Financial-Times/o-header#sass, This doesn't seem to affect prod but was causing errors when building storybook locally.
=> Remove 'top' as a oHeader sass option

packages/dotcom-ui-header/src/__stories__/story.tsx
A small tidy-up to the labels we use to identify the layout variants in our header storybook. These labels better reflect how we refer to possible header variants in the rest of the codebase.
=> Update the labels for the storybook logo only demo

examples/kitchen-sink/client/main.js, examples/kitchen-sink/package.json
Bumped n-ads to latest version. n-ads v2 updates all the dependencies to latest version. n-ads v3 now requires `appContext` to be passed in as an option when being initialised.
=> Bump n-ads

packages/dotcom-ui-header/README.md, packages/dotcom-ui-header/src/__stories__/story.tsx, packages/dotcom-ui-header/src/index.tsx, packages/dotcom-ui-header/src/interfaces.d.ts
Please let me know if I've missed anything but as far as I can tell, this option will be able to be passed through using the `headerOptions` of the `Layout` component.
=> Add showLogoLink option to logo only header

docs/design-decisions/app-context.md, examples/ft-ui/client/main.js, examples/ft-ui/package.json, examples/kitchen-sink/client/main.js, examples/kitchen-sink/package.json, packages/dotcom-build-code-splitting/src/plugin.ts, packages/dotcom-ui-bootstrap/readme.md, scripts/generate-storybook-config.js
Fixes: https://github.com/Financial-Times/dotcom-page-kit/issues/740.
Once this PR is approved I will make the necessary changes in the migration docs: https://github.com/Financial-Times/dotcom-page-kit/wiki/Migrating-from-n%E2%80%93ui-to-Page-Kit.
@apaleslimghost Re. your [comment](https://github.com/Financial-Times/n-tracking/pull/39/files#r373430152) in this n-tracking PR:
- Should we also be using the `ready-state` package in that repo (or have Page Kit wrap it in a function that it can use)?
- Do we also need to identify which other apps that consume Page Kit likewise need this change applied?
- [npm: ready-state](https://www.npmjs.com/package/ready-state).
=> Replace dom-loaded with ready-state

examples/ft-ui/__test__/logged-in-user.test.js, packages/dotcom-ui-layout/src/components/Layout.tsx, scripts/generate-storybook-config.js
I think these Prettification changes must have slipped through without the Git hook (that runs `npm run prettier`) being applied (i.e. commits made via GitHub GUI or commit made with `--no-verify`).
Each time I make a commit, `npm run prettier` gets run as the Git hook and I have to then remember to reset the changes it has applied to prevent them from being included in my next commit (where they would not be relevant to that specific commit).
So it seems to make sense to give them their own little commit here where they get applied and stop causing this problem.
=> Apply Prettier

package.json
previously, if files had slipped through without being formatted, they could be changed in later, unrelated commits, but not written to that commit by `git add`.
this makes sure that only the files staged in the commit get formatted, preventing changes to unrelated files going uncommitted.
this works because `lint-staged` passes the list of staged files as arguments to the commands.
see #748
=> change lint-staged rules to only format staged files

examples/combined-hbs-jsx/views/Home.jsx, examples/combined-hbs-jsx/views/home.hbs
=> Correct background-color for combined-hbs-jsx example

packages/dotcom-ui-header/README.md, packages/dotcom-ui-header/src/__stories__/story.tsx, packages/dotcom-ui-header/src/index.tsx
Extension of work done in this PR https://github.com/Financial-Times/dotcom-page-kit/pull/741 to enable the link for the `MainHeader` component to be switched on/off as it can for the `LogoOnly` header.
=> Enable MainHeader logo link to be switched off

packages/dotcom-build-sass/README.md, packages/dotcom-build-sass/package.json, packages/dotcom-build-sass/src/plugin.ts
Fixes https://github.com/Financial-Times/dotcom-page-kit/issues/678.
Switches from using LibSass to Dart Sass for Sass implementation.
Work was validated by running `npm run build` in `./examples/ft-ui` having added the below lines to its `/client/main.scss` file.
```scss
@if true {
$not-already-defined: true !global;
}
```
Dart Sass throws a warning if a global variable is defined outside of global scope, which LibSass doesn't.
To ensure warnings are enabled you can add to the `main.scss` file the below line which outputs a warning.
```scss
@warn 'warning text';
```
---
- Testing of this Page Kit branch with consuming apps to ensure that `n-` components are spec compliant.
- [Sass: Dart Sass](https://sass-lang.com/dart-sass).
- [GitHub: webpack-contrib/sass-loader - …
=> Use Dart Sass for Sass implementation

changelog.md, packages/dotcom-server-handlebars/src/PageKitHandlebars.ts
The upcoming n-messaging-client release uses `server/templates` not `templates`.
=> add server/templates to the list of directories to search for partials

packages/dotcom-server-handlebars/package.json
this is working as-is and not breaking tests because most things that depend on dotcom-server-handlebars also depend on one of the `dotcom-ui-` packages, which have `react` as a dependency, which gets flattened
=> add missing react dependency to dotcom-server-handlebars

packages/dotcom-ui-header/README.md
We wrote a nice Readme for unread-articles-indicator so maybe it is better to link to the readme instead of a particular line?
=> Update unread-articles-indicator link

packages/dotcom-page-kit-cli/src/utils/pack.ts
To reveal the (Webpack) error being thrown here: https://circleci.com/gh/Financial-Times/next-url-mgmt-service/152.
=> Modify CLI package Webpack error with check for stats

packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Content.test.tsx.snap, packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap, packages/dotcom-ui-shell/src/components/Content.tsx
because `contents` is either a string or a `ReactNode`, we can be sure it's a `ReactNode` here and return it directly (having said that, it doesn't typecheck 🤔)
=> don't output wrapper div if contents is a react node

packages/dotcom-ui-footer/src/components/partials.tsx
As o-footer already uses the `footer` element, this results in
two `contentinfo` landmarks. There **should** only be one.
Relates to: https://github.com/Financial-Times/o-footer/pull/128
=> Remove `role="contentinfo"` from `o-footer` markup.

packages/dotcom-ui-base-styles/src/lib/fontFaces.ts, packages/dotcom-ui-base-styles/styles.scss, packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap
Origami team has recently updated fonts with a new font https://github.com/Financial-Times/o-fonts-assets/releases/tag/v1.4.0. Note that this PR isn't shipping any new fonts, only updating the o-asset-fonts links
=> Updating version of o-fonts-assets

packages/dotcom-middleware-app-context/src/__test__/index.spec.ts, packages/dotcom-middleware-asset-loader/src/__test__/index.spec.ts
Removes two test expectations which call `toHaveLength()` on Function values. 
I'm not sure what the original intention was but this usage is pretty unexpected (usually only strings and arrays have `length` properties) and it's not reflected in the examples given in the jest docs. https://jestjs.io/docs/en/expect#tohavelengthnumber
Both test conditions seem to be covered by remaining expectations so it should be safe to remove these.
=> Remove tests which expect the length of a function

packages/dotcom-ui-header/bower.json, packages/dotcom-ui-header/src/components/navigation/partials.tsx
The nav items in the masthead are inline and still showing on small screens causing elements to run into each other. The subscribe button is now hidden on smaller screens.
I've tested this locally and got the desired result but would appreciate someone else testing as well to make sure
After:
Before:
=> NOPS-71: Hide subscribe sticky nav button when screen is small

packages/dotcom-middleware-navigation/src/handleEdition.ts
`next-control-centre`'s CircleCI build has a step that runs `make build-production`, which in turn runs TypeScript checks (`tsc`): https://github.com/Financial-Times/next-control-centre/blob/master/Makefile#L44.
These have started to fail; the reason why they have started now is unclear.
See: https://circleci.com/gh/Financial-Times/next-control-centre/4921.
```
node_modules/@financial-times/dotcom-middleware-navigation/src/handleEdition.ts:14:42 - error TS2345: Argument of type 'string | string[] | Query | Query[]' is not assignable to parameter of type 'string'.
Type 'string[]' is not assignable to type 'string'.
14   if (request.query.edition && isEdition(request.query.edition)) {
~~~~~~~~~~~~~~~~~~~~~
node_modules/@financial-times/dotcom-middleware-navigation/src/handleEdition.ts:15:5 …
```
=> Fix middleware-navigation TypeScript errors

packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap, packages/dotcom-ui-shell/src/components/Shell.tsx
This causes a font loading race condition in Chrome that means sometimes,
although fonts have loaded, we don't remove the classes from the body,
so the fallback fonts are displayed.
This reverts commit 721eb24363a2a26d3809f993e2afd9c01c0bf63b.
https://financialtimes.atlassian.net/browse/NOPS-120
=> Revert "Relocate LoadFontsEmbded prior to Stylesheets for minor performance optimisation"

packages/dotcom-ui-layout/browser.js, packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap, packages/dotcom-ui-shell/src/components/Shell.tsx
welp. fun fact: font loading has never worked with Page Kit! "but bren," i hear you ask, "yes they have what the heck?", well:
- by default, we add font loading classes to the `<html>` element, which forces o-typography to use the fallback fonts while fonts load
- there's a separate bit of code to remove the loading classes if the fonts have already loaded; `o-typography` uses a cookie, `o-typography-fonts-loaded`, to signal this
- `dotcom-ui-layout`'s init calls `oTypography.init` on the `.n-layout` element. it's supposed to load the fonts and set the cookie, but it has no effect, because that element doesn't have `data-o-component="o-typography"` [any more](https://github.com/Financial-Times/dotcom-page-kit/pull/770/files#diff-b7d9d78266cd0478e141461d7d6f73a0L83)
- …
=> fix fonts loading

roadmap.md
Updates the roadmap with the remaining significant changes that we plan to make ahead of our first stable v1.x.x release.
=> add v0.8.x and v0.9.x releases to the roadmap

package.json
TypeScript does not follow Semantic Versioning.
This means that the caret (^) syntax used by npm installed a breaking version, as it expects minor and patch releases to be backwards compatible.
This unfortunately means we need to pin the dependency to ensure our code does not break.
> export * is Always Retained
> In previous TypeScript versions, declarations like export * from "foo" would be dropped in our JavaScript output if foo didn’t export any values. This sort of emit is problematic because it’s type-directed and can’t be emulated by Babel. TypeScript 3.9 will always emit these export * declarations. **In practice, we don’t expect this to break much existing code, but bundlers may have a harder time tree-shaking the code.** …
=> Fix master: Pin TypeScript dependency

packages/dotcom-ui-base-styles/bower.json, packages/dotcom-ui-base-styles/src/lib/fontFaces.ts, packages/dotcom-ui-base-styles/styles.scss, packages/dotcom-ui-layout/bower.json, packages/dotcom-ui-shell/src/__test__/components/ResourceHints.test.tsx, packages/dotcom-ui-shell/src/__test__/components/__snapshots__/ResourceHints.test.tsx.snap, packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap, packages/dotcom-ui-shell/src/__test__/lib/getResourceType.spec.ts, packages/dotcom-ui-shell/src/lib/getResourceType.ts
The latest version of o-fonts-assets includes woff2 formats
for a significant reduction in filesize:
https://github.com/Financial-Times/o-fonts-assets/pull/19
It looks like more browsers support woff2 than
`<link rel="preload">`, so it is safe to update the preloads
to the woff2 format.
https://caniuse.com/#search=woff2
https://caniuse.com/#search=preload
Bonus: When projects which depend on page kit are re-deployed
the double font download issue caused by the preload
o-fonts-assets version being different will be resolved
(for now, unless they diverge again):
https://financialtimes.slack.com/archives/C3TJ6KXEU/p1590161366213400
=> Use the latest version of o-fonts-assets and o-typography.

packages/dotcom-ui-header/README.md, packages/dotcom-ui-header/src/__stories__/story.tsx, packages/dotcom-ui-header/src/__test__/components/NoOutboundLinks.spec.tsx, packages/dotcom-ui-header/src/__test__/components/__snapshots__/NoOutboundLinks.spec.tsx.snap, packages/dotcom-ui-header/src/index.tsx, packages/dotcom-ui-layout/README.md, packages/dotcom-ui-layout/src/components/Layout.tsx, packages/dotcom-ui-layout/src/components/__test__/Layout.spec.tsx
I'm working on a card that needs to remove any outbound links in the header that may lead to content / a barrier due to iOS complications.
Apps on iOS have to pay a percentage of any subscriptions taken via the app directly to Apple so to try and mitigate the frequency of this, we want to have a header that is used on the `MyAccount` section of the website (one of the few areas of the website that is embedded on the app) that removes any links that may link to content and potentially a barrier page.
Happy to discuss options!
https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1108&projectKey=ACC&modal=detail&selectedIssue=ACC-396
Desktop Anon:
Desktop Logged In:
Mobile Logged In:
Mobile Anon:
=> feat: add new header variant aimed at app users (ACC-396)

renovate.json
I've moved the out of hours configuration into the main configuration here:
https://github.com/Financial-Times/renovate-config-next/pull/43
=> Use shared renovate configuration

packages/dotcom-ui-app-context/README.md, packages/dotcom-ui-data-embed/README.md, packages/dotcom-ui-flags/README.md
This is so they do not block the render of the page, and matches how they're used in the `dotcom-ui-shell` package.
This is a simple change, I think we may need to explain more about ordering explicitly but I'm thinking we do this first and see if it comes up again.
Closes https://github.com/Financial-Times/dotcom-page-kit/issues/822
=> Recommend rendering some scripts at end of the document

packages/dotcom-ui-shell/src/components/ResourceHints.tsx
The comment that accompanies the link to `https://session-next.ft.com` cites the repo for [`next-session-client`](https://github.com/Financial-Times/next-session-client).
However, it is actually [`next-session`](https://github.com/Financial-Times/next-session) that provides that endpoint (as described by its README), which the link points to without employing `next-session-client`.
I randomly encountered this while investigating whether we can remove `next-session-client` and so was scrutinising all of its mentions.
=> Correct comment referencing next-session-client -> next-session

changelog.md, packages/dotcom-ui-base-styles/bower.json, packages/dotcom-ui-header/bower.json, packages/dotcom-ui-layout/bower.json
Since Page kit depends on [n-topic-search](https://github.com/Financial-Times/n-topic-search/pull/34) I'd expect this to blow up, raising out of curiosity to learn more about bower dependency resolution...
Update: it did! So that's good :P Hopefully we'll see it pass once we include a new version of n-topic-search
- [`n-ui-foundations` Migration guide v5 to v6](https://github.com/Financial-Times/n-ui-foundations#user-content-v5-to-v6).
=> Update n-ui-foundations to v6.0.0

examples/ft-ui/README.md, examples/ft-ui/client/main.js, examples/ft-ui/package.json, packages/dotcom-privacy-footer-localiser/README.md
Adding examples of use of the new `dotcom-privacy-footer-localiser` to the `ft-ui` example
=> Footer localiser example

examples/building-sass-files/__test__/integration.test.js, examples/building-sass-files/webpack.config.js, packages/dotcom-build-sass/README.md, packages/dotcom-build-sass/src/index.ts
`dotcom-page-kit` uses `n-ui-foundations` in some of its packages and so was included as part of the [`n-ui-foundations` v5 to v6 migration](https://github.com/Financial-Times/n-ui-foundations#user-content-v5-to-v6) - see: https://github.com/Financial-Times/dotcom-page-kit/pull/839.
When making the final updates to a user-facing app (i.e. the endpoint of the migration), the styling of the header and footer components does not remain consistent with production:
It is caused by `o-header` using the `oGridContainer` mixin, which used to inherit the global snappy grid setting, but the global snappy setting has now been removed from `n-ui-foundations`.
Currently, these classes are added to the CSS: `o-header__container--snappy` and `o-footer__container--snappy`, but we cannot add those classes …
=> Add prependData option to dotcom-build-sass

packages/dotcom-ui-header/src/__test__/components/__snapshots__/MainHeader.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/components/__snapshots__/NoOutboundLinks.spec.tsx.snap, packages/dotcom-ui-header/src/components/sub-navigation/partials.tsx
The class `o-header__subnav-list--subsections` does not exist.
Instead it should be `o-header__subnav-list--children`.
This will increase the padding between subnav items for PageKit
projects, which is currently too small.
=> Correct subnav markup

packages/dotcom-ui-header/bower.json, packages/dotcom-ui-header/src/header.scss
- drawer css has been added to o-header: https://github.com/Financial-Times/o-header/releases/tag/v8.5.0
- sticky `display` was immediately reset to block so can be removed
- myft relative positioning was added for an old tooltip: https://github.com/Financial-Times/n-ui/pull/592
- sticky header is hidden for print as part of o-header: https://github.com/Financial-Times/o-header/blob/d93390313442713629da29b470b44f42e77f90d8/src/scss/features/_sticky.scss#L17
=> Upgrade o-header to 8.5.0.

packages/dotcom-build-base/package.json
Jira card: [CPP-357 dotcom-page-kit - Address arbitrary code injection vulnerability](https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1051&modal=detail&selectedIssue=CPP-357)
Fixes vulnerability reported by Snyk: https://app.snyk.io/org/financial-times/project/dd7eb820-a794-407f-8653-6ce9f4ab1a38#issue-SNYK-JS-SERIALIZEJAVASCRIPT-570062.
> **Detailed paths and remediation**
> - Introduced through: @financial-times/dotcom-build-base@0.0.0 › compression-webpack-plugin@3.1.0 › serialize-javascript@2.1.2
> - Remediation: Upgrade to compression-webpack-plugin@4.0.0
The breaking changes between version 3 and 4 of `compression-webpack-plugin` relate to parts of the package that I cannot see are being used: https://github.com/webpack-contrib/compression-webpack-plugin/release …
=> Upgrade dotcom-build-base compression-webpack-plugin dev dependency ^3.0.0 -> ^4.0.0

packages/dotcom-ui-shell/src/__test__/components/__snapshots__/DocumentHead.test.tsx.snap, packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap, packages/dotcom-ui-shell/src/components/DocumentHead.tsx
[Docs](https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners)
This [used to exist in n-ui][1] but was removed during the migration to Page Kit.
You can verify the app-id parameter here: https://apps.apple.com/app/apple-store/id1200842933
[1]: https://github.com/Financial-Times/n-ui/blob/07149f43/browser/layout/wrapper.html#L38
---
This is probably the first time I've ever done React, TypeScript, JSX or whatever it is we're actually doing here.
=> [NOPS-103] Add Smart App Banner for the iOS app

packages/dotcom-server-app-context/src/index.ts, packages/dotcom-ui-bootstrap/src/components/Bootstrap.tsx, packages/dotcom-ui-flags/src/components/FlagsEmbed.ts, packages/dotcom-ui-header/src/index.tsx, packages/dotcom-ui-shell/src/components/Shell.tsx, tsconfig.json
This PR adds --isolatedModules with a value of `true` to tsconfig. 
Some packages in this workspace re-exports modules imported as types as regular modules and not types. 
It is difficult to track which imports should be `types` or `modules` without  ` --isolatedModules` the flag. This is the case because of the export flow which leaves the decision of the export type (type || module) to the parent file.
See https://www.typescriptlang.org/tsconfig#isolatedModules for more information.
=> added isolatedModules field to tsconfig

packages/dotcom-types-navigation/index.d.ts, packages/dotcom-ui-header/src/__stories__/story-data/drawerUK.ts, packages/dotcom-ui-header/src/__test__/components/__snapshots__/Drawer.spec.tsx.snap, packages/dotcom-ui-header/src/components/drawer/additionalPartials.tsx, packages/dotcom-ui-header/src/components/drawer/topLevelPartials.tsx
This is enabling a second level drawer submenu in the dotcom-ui-header.
=> Hive 279 drawer amend

.circleci/config.yml, package.json, packages/dotcom-build-base/package.json, packages/dotcom-build-bower-resolve/package.json, packages/dotcom-build-code-splitting/package.json, packages/dotcom-build-images/package.json, packages/dotcom-build-js/package.json, packages/dotcom-build-sass/package.json, packages/dotcom-middleware-app-context/package.json, packages/dotcom-middleware-asset-loader/package.json, packages/dotcom-middleware-navigation/package.json, packages/dotcom-server-app-context/package.json, packages/dotcom-server-asset-loader/package.json, packages/dotcom-server-handlebars/package.json, packages/dotcom-server-navigation/package.json, packages/dotcom-server-react-jsx/package.json, packages/dotcom-types-navigation/package.json, packages/dotcom-ui-app-context/package.json, packages/dotcom-ui-base-styles/package.json, packages/dotcom-ui-bootstrap/package.json, packages/dotcom-ui-data-embed/package.json, packages/dotcom-ui-flags/package.json, packages/dotcom-ui-footer/package.json, packages/dotcom-ui-header/package.json, packages/dotcom-ui-layout/package.json, packages/dotcom-ui-polyfill-service/package.json, packages/dotcom-ui-shell/package.json
We are moving to npm 8 so we are ready to migrate away from bower. There was one breaking change where `jest-puppeteer` so that the newer version of `puppeteer` we were using was within its peer dependency requirements. The major update does not seem to have affected any other behaviour. Apart from that, it was as simple as pinning a new npm version with volta (you can also update your npm globally to test the changes) and making sure CircleCI uses the right npm version too. We have added a `preinstall` script to each package's `package.json` that will make sure that npm 8 is selected when running an install.
=> CPP-675 Update to npm 8

packages/dotcom-ui-header/package.json
logo-images is a origami component too, which needs to be added as a peer dep
=> add logo-images as peer dep

packages/dotcom-ui-bootstrap/package.json, packages/dotcom-ui-data-embed/package.json, packages/dotcom-ui-flags/package.json, packages/dotcom-ui-footer/package.json, packages/dotcom-ui-header/package.json, packages/dotcom-ui-layout/package.json, packages/dotcom-ui-shell/package.json
Page Kit packages currently only allow React v16 as peerDependencies. This should be widened to allow version 17 to unblock the content disco team. We could also add v18, but it's only on 18.0.0-rc.0, so not sure we'd want to do that yet?
=> cpp-722 widen react versions for peer deps

contribution.md
this was for the initial development of page kit but we don't follow it any more
=> remove git workflow from contribution guide

packages/dotcom-ui-shell/README.md, packages/dotcom-ui-shell/src/__test__/components/DocumentHead.test.tsx, packages/dotcom-ui-shell/src/components/DocumentHead.tsx
Page Kit consumers will be able to decide whether they want iOs Smart Banner or not on their page.
Passing `showSmartBanner` prop as false, will not render the `apple-itunes-app` meta tag. This will be used by next-subscribe so we can hide the smart banner for users which are already using the app on subs journey.
=> Added showSmartBanner to DocumentHead

.circleci/config.yml
use the exact npm version of 8.5.3 in circleci (as per volta pin in package.json) to fix [test step not bundling o-toggle ](https://app.circleci.com/pipelines/github/Financial-Times/dotcom-page-kit/4106/workflows/166a0a4d-3d4a-479c-aa8d-9d443f2e811e/jobs/7522)
=> update to use npm 8.5.3 in circleci config.yml

.circleci/config.yml, examples/ft-ui/__test__/anonymous-user.test.js, examples/ft-ui/__test__/logged-in-user.test.js, examples/ft-ui/__test__/subscribed-user.test.js, examples/ft-ui/server/controllers/home.jsx, examples/kitchen-sink/__test__/integration.test.js, packages/dotcom-ui-header/package.json, packages/dotcom-ui-header/src/__stories__/story.tsx, packages/dotcom-ui-header/src/__test__/components/__snapshots__/MainHeader.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/components/__snapshots__/StickyHeader.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/enzyme/component.spec.tsx, packages/dotcom-ui-header/src/components/navigation/partials.tsx, packages/dotcom-ui-header/src/components/sticky/partials.tsx, packages/dotcom-ui-header/src/components/top/partials.tsx, packages/dotcom-ui-header/src/index.tsx, packages/dotcom-ui-header/src/interfaces.d.ts, packages/dotcom-ui-layout/package.json
**Description**
Relocate header's top right buttons, and include Subscribe button for user registered but not subscribed. It depends on headerOptions sent by the consumer. The user status needed are filled in n-express [here](https://github.com/Financial-Times/n-express/blob/3aba289da097f64a7e7dbf44821000fa823d35ba/src/middleware/anon.js#L10)
https://financialtimes.atlassian.net/browse/ACQ-1535
**Screenshots**
**User subscribed**
**User logged in**
**User logged out**
=> ACQ-1535: relocate nav and top buttons

packages/dotcom-server-navigation/src/actions.ts
Segment ID for subscribe button in Drawer menu was wrong.
This is not likely to change anymore in the future, there was just an error on Analytics requirements.
=> ACQ-1605: correct segmentId for subscribe button in drawer menu

packages/dotcom-ui-layout/package.json
Remove o-typogragy from dotcom-ui-layout since it was not used there.
**Context**: https://financialtimes.slack.com/archives/C3TJ6KXEU/p1651072879410939?thread_ts=1651072094.582689&cid=C3TJ6KXEU
=> ACQ-1621: remove o-typogragy from ui-layout since was unneeded

examples/building-sass-files/__test__/integration.test.js, examples/kitchen-sink/__test__/build.test.js, packages/dotcom-build-js/README.md, packages/dotcom-build-js/src/babel.ts, packages/dotcom-build-sass/src/index.ts
The regenerator runtime is used to support polyfills of generator functions. It stopped being output by Webpack since the last commit to main, possibly because all dependencies that were using it have been updated to no longer require it and it is now tree shaken? Fortunately, after updating our browserslist config to the [current browsers we support](https://docs.google.com/document/d/1z6kecy_o9qHYIznTmqQ-IJqre72jhfd0nVa4JMsS7Q4), we no longer need the Babel transform as all of our supported browsers now support generators, so we can safely assume it is not a required Webpack bundle.
=> Fix kitchen sink test

__fixtures__/menus.json, packages/dotcom-ui-header/src/__stories__/story-data/navbarUK.ts, packages/dotcom-ui-header/src/__test__/components/__snapshots__/MainHeader.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/components/__snapshots__/StickyHeader.spec.tsx.snap
Rename the navigation label from "How To Spend It" to "HTSI"
for more info see [this Slack thread](https://financialtimes.slack.com/archives/C04RUBL9G/p1654008631395689)
=> rename HTSI label

packages/dotcom-server-navigation/package.json, packages/dotcom-server-navigation/src/navigation.ts
This is a breaking change in ft-poller which fixes a bug in that nothing listening to the `emit('error')` event results in an unhandled promise rejection warning that causes Node 16 apps to crash. It also drops support for Node 12.
See https://github.com/Financial-Times/ft-poller/pull/91 for context.
This change appears to be the first use of n-logger in Page Kit.
=> Upgrade ft-poller from v5 to v7

packages/dotcom-ui-header/README.md
Update docs to reflect `userIsSubscribed` option for Header
Ticket: https://financialtimes.atlassian.net/browse/ACQ-1754
=> ACQ-1754: Update docs userIsSubscribed option for Header

packages/dotcom-middleware-app-context/package.json, packages/dotcom-middleware-asset-loader/package.json
The latest version of `@types/express-serve-static-core` causes our TypeScript builds to fail as it uses syntax that our older version of `tsc` can't parse (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/62300). Let's force it to use an older version to avoid this.
In theory, it would be better to use npm overrides to achieve this, but I can't get it to work in practice as they always seem to fail to handle one instance of a transitive dependency or other.
We could also work around this by updating to the latest version of `tsc` – which might be worthwhile but could introduce some other bugs I don't want to search for right now, or finally add a `package-lock.json` file to this monorepo. I think npm workspaces would be a suitable drop-in for the athloi workflow we have at the …
=> Use version of express-serve-static-core type definition compatible with TypeScript 3.x

packages/dotcom-server-navigation/package.json, packages/dotcom-server-navigation/src/navigation.ts
Removed need for try/catch as latest version of ft-poller no longer throws and error.
=> CPREL-336: Fix dotcom-server-navigation by updating and improving ft-poller handling

packages/dotcom-types-navigation/index.d.ts, packages/dotcom-ui-header/src/components/drawer/additionalPartials.tsx, packages/dotcom-ui-header/src/components/drawer/topLevelPartials.tsx, packages/dotcom-ui-header/src/components/navigation/partials.tsx, packages/dotcom-ui-header/src/components/sticky/partials.tsx, packages/dotcom-ui-header/src/components/sub-navigation/partials.tsx, packages/dotcom-ui-header/src/components/top/partials.tsx, packages/dotcom-ui-header/tsconfig.json
We have aligned our navigation types to allow for `sectionlist` and `articlelist` to be `null` or `undefined`. The Origami Navigation Services allow for these type to be null but our templates did not reflect this. Our templates failed to render in https://github.com/Financial-Times/incident-reports/issues/534 when the data expected was not an array.
We have now fixed the type definition and fixed the typescript config to check for null types just for the `dotcom-ui-header` (it was turned off very early in this repo for everything and never turned back on). Turning on `strictNullChecks` means new type errors have been exposed for the package which this PR fixes.
=> CPREL-337: Fix navigation type checking and add rendering fallbacks if Menu Items are missing

packages/dotcom-ui-header/src/__test__/components/__snapshots__/Drawer.spec.tsx.snap, packages/dotcom-ui-header/src/components/drawer/topLevelPartials.tsx, packages/dotcom-ui-header/src/components/navigation/partials.tsx
As discussed with Alex and Glynn in the conversation below I am submitting this PR to add `data-component` attributes to `NavListLoggedIn` and `Drawer` so we could target and add Workspace nav item with a tooltip.
https://financialtimes.slack.com/archives/CSH1XFM5W/p1665494436384209
=> Add targets for workspace menu

packages/dotcom-build-base/package.json
The PR codifies that the dotcom-build-base package works with Webkit 5.x.x. The work to actually add support was completed a long time ago in [CPP-538](https://financialtimes.atlassian.net/browse/CPP-538).
I opted to keep v4 of Webkit at `^4.39.2` instead of `4.x.x` because I don't know what level of support there is for earlier versions of the 4.x branch. Let me know if you'd rather go with `4.x.x` to match `@dotcom-tool-kit/webpack`.
=> chore(dotcom-build-base): widen Webpack version range

packages/dotcom-build-base/package.json
Reverts Financial-Times/dotcom-page-kit#959
It seems that Webpack 5 has dropped support for TypeScript 3, causing the CircleCI build to fail. Rather than rush to make a decision about how to work around this (should we update to TypeScript 4? etc...) let's discuss this within the @Financial-Times/platforms team, and revert this PR for now.
=> Revert "chore(dotcom-build-base): widen Webpack version range"

package.json, packages/dotcom-build-sass/package.json, packages/dotcom-build-sass/src/index.ts, packages/dotcom-middleware-app-context/package.json, packages/dotcom-middleware-asset-loader/package.json
Seeing as we still aren't using a lockfile for this repository we're occasionally bumping into `@types` definitions which are doing minor version updates that are breaking TypeScript 3.x support. We need to pin the version of `@types/babel__traverse` that Jest uses in order to avoid one such compatibility issue.
=> Fix TypeScript build errors

packages/dotcom-build-sass/src/index.ts
Force the Webpack PostCSS loader to use the PostCSS dependency version for the package.
=> CPP-1043: Define postcss implementation for loader options for dotcom-build-sass package

examples/ft-ui/__test__/anonymous-user.test.js, examples/ft-ui/__test__/logged-in-user.test.js, examples/ft-ui/__test__/subscribed-user.test.js
https://github.com/Financial-Times/origami-navigation-service/pull/533 updated the `href` link for the 'Settings & Account' button in the ft.com header to be relative rather than absolute. We were testing that this element was being showing up properly when the user was signed in our integration tests, but we were selecting it by the now modified `href` attribute.
I've updated the selector to search for the new relative `href` attribute. I've also made the selector more permissive: it will find any element that _ends_ in the relative link rather than matching it exactly. It looks like Origami is planning on potentially reverting back to absolute links at some point and this more permissive selection now shouldn't break even if that change is made. Therefore, I've extended that change to …
=> Fix failing integration tests by mirroring Navigation API change

packages/dotcom-build-sass/src/index.ts
This PR fixes a bug from #964, where the `implementation` option was set for the `postcss-loader` plugin, but nested in the `postcssOptions` object when it [was meant to be outside of it](https://www.npmjs.com/package/postcss-loader#implementation). This meant that the `implementation` options was being silently ignored, and we were still running into the same resolution issues reported in the [ticket](https://financialtimes.atlassian.net/browse/CPP-1043) associated with that PR. This PR should fix that.
I was hoping that there would be a TypeScript definition for the `postcss-loader` options object so that we wouldn't run into issues like this in the future, but it seems like that doesn't exist (even though the docs are clear about what the type of each option is!) The docs are quite …
=> Put postcss-loader option in correct place

packages/dotcom-ui-header/package.json, packages/dotcom-ui-header/src/__test__/components/__snapshots__/Drawer.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/enzyme/drawer.spec.tsx, packages/dotcom-ui-header/src/components/drawer/topLevelPartials.tsx
Update the `o-header` to v11 to get the latest accessibility audit updates. Followed the [migration script](https://github.com/Financial-Times/origami/blob/o-header-v11.0.4/components/o-header/MIGRATION.md#markup-drawer-divider) to manually apply the changes.
=> CPP-1242: Update o-header dependency to v11

.circleci/config.yml
I forgot to specify the workspace in the `npm publish` workflow 🤦‍♂️ This will fix our publish step.
=> fix: only publish the packages workspace

packages/dotcom-build-base/package.json, packages/dotcom-build-code-splitting/package.json, packages/dotcom-build-images/package.json, packages/dotcom-build-js/package.json, packages/dotcom-build-sass/package.json, packages/dotcom-middleware-app-context/package.json, packages/dotcom-middleware-asset-loader/package.json, packages/dotcom-middleware-navigation/package.json, packages/dotcom-server-app-context/package.json, packages/dotcom-server-asset-loader/package.json, packages/dotcom-server-handlebars/package.json, packages/dotcom-server-navigation/package.json, packages/dotcom-server-react-jsx/package.json, packages/dotcom-types-navigation/package.json, packages/dotcom-ui-app-context/package.json, packages/dotcom-ui-base-styles/package.json, packages/dotcom-ui-bootstrap/package.json, packages/dotcom-ui-data-embed/package.json, packages/dotcom-ui-flags/package.json, packages/dotcom-ui-footer/package.json, packages/dotcom-ui-header/package.json, packages/dotcom-ui-layout/package.json, packages/dotcom-ui-polyfill-service/package.json, packages/dotcom-ui-shell/package.json
Before the migration to npm workspaces for publishing, we used to ignore a select group of files. Now we define the files to publish, we need to add the missing files that have not been defined but are required.
=> CPP-1317: fix missing files to publish in each package

.circleci/config.yml, package.json
When publishing to the npm registry, we set the version in each Page Kit package dependency. Athloi used to then update each Page Kit package Page Kit dependency to the latest version number. This is missing in the migration to npm workspaces (CPP-1249).
We can use athloi just for the version step. We should then replace this with release-please.
https://financialtimes.atlassian.net/browse/CPP-1330
=> CPP-1330: fix publish versions of each package Page Kit dependency

packages/dotcom-ui-bootstrap/package.json
As part of the runtime import of the `dotcom-ui-bootstrap`, it requires being able to get the script string stored in `lib/bootstrap.js` (see [server/getBootstrapJS.ts](https://github.com/Financial-Times/dotcom-page-kit/blob/76f9be1f9ff22cb5fd2bdbb599dec4d5477430c0/packages/dotcom-ui-bootstrap/src/server/getBootstrapJS.ts#L4)). However, when publishing this package, the current `package.json` doesn't include the `lib` directory as part of the published files so the code can't find it.
=> Include lib/ required by getBootstrapJS

packages/dotcom-ui-header/src/__test__/components/__snapshots__/StickyHeader.spec.tsx.snap, packages/dotcom-ui-header/src/components/sticky/partials.tsx
When navigating through the navigation elements via the keyboard, the hidden sticky nav’s “subscribe“ button is in the tab index. This will element will be read highlighted to a user using assistive technologies which can cause a confusing experience.
=> fix(dotcom-ui-header): add negative tab index to sticky subscribe button

.circleci/config.yml, package.json, packages/dotcom-build-base/package.json, packages/dotcom-build-code-splitting/package.json, packages/dotcom-build-images/package.json, packages/dotcom-build-js/package.json, packages/dotcom-build-sass/package.json, packages/dotcom-middleware-app-context/package.json, packages/dotcom-middleware-asset-loader/package.json, packages/dotcom-middleware-navigation/package.json, packages/dotcom-server-app-context/package.json, packages/dotcom-server-asset-loader/package.json, packages/dotcom-server-handlebars/package.json, packages/dotcom-server-navigation/package.json, packages/dotcom-server-react-jsx/package.json, packages/dotcom-types-navigation/package.json, packages/dotcom-ui-app-context/package.json, packages/dotcom-ui-base-styles/package.json, packages/dotcom-ui-bootstrap/package.json, packages/dotcom-ui-data-embed/package.json, packages/dotcom-ui-flags/package.json, packages/dotcom-ui-footer/package.json, packages/dotcom-ui-header/package.json, packages/dotcom-ui-layout/package.json, packages/dotcom-ui-polyfill-service/package.json, packages/dotcom-ui-shell/package.json
To be merged as part of breaking changes releases on week of 17th April
update engines field to only support Node.js 16 for now, using the agreed engines specification format - https://docs.google.com/document/d/1i1on1ZiFwQITlTDsbaQO_uOtugDxeV5bmAVaSVXe_Mo/edit#
update circle CI config to only build on Node.js 16
=> feat: drop support for Node.js 14

packages/dotcom-ui-header/browser.js, packages/dotcom-ui-header/package.json, packages/dotcom-ui-header/src/components/drawer/topLevelPartials.tsx, packages/dotcom-ui-header/src/enhanced-search/customList.js, packages/dotcom-ui-header/src/enhanced-search/enhancedSearch.js, packages/dotcom-ui-header/src/enhanced-search/styles.scss, packages/dotcom-ui-header/src/index.tsx, packages/dotcom-ui-header/src/interfaces.d.ts, packages/dotcom-ui-header/styles.scss, packages/dotcom-ui-header/tsconfig.json
In this repo I have changed the approach we are adding the flyout to the dotcom-ui-header by extending the already existing n-topic-search 
there should be no changing in the UI
=> Eles 753 modify dotcom UI header to load new UI component

packages/dotcom-ui-header/src/enhanced-search/customList.js, packages/dotcom-ui-header/src/enhanced-search/styles.scss
In this PR I have updated the UI for the enhanced-search-flyout by updating max-width, and paddings
[JIRA ELES-800](https://financialtimes.atlassian.net/browse/ELES-800)
[figma](https://www.figma.com/file/Hjz28uiQqs8pxUm6X7fCG5/FT.com_Search_Test?type=design&node-id=1652-1663&mode=design&t=rLW08eQlkduo7XPI-4)
| Before    | After |
| -------- | ------- |
|  <img width="1169" alt="Screenshot 2023-09-07 at 5 25 19 PM" src="https://github.com/Financial-Times/dotcom-page-kit/assets/139355573/6201bf85-b1d0-41bc-9a67-a0aefbf1cfbf">|<img width="1169" alt="Screenshot 2023-09-07 at 5 24 52 PM" src="https://github.com/Financial-Times/dotcom-page-kit/assets/139355573/91d8c61e-e191-4caf-9cf5-5ae12190b061"> |
=> Eles 800 adjust alignment and padding of flyout menu toms tweak

packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap, packages/dotcom-ui-shell/src/components/DocumentHead.tsx
From Semrush: "Duplicate meta descriptions on different pages mean a lost opportunity to use more relevant keywords. Also, duplicate meta descriptions make it difficult for search engines and users to differentiate between different webpages. It is better to have no meta description at all than to have a duplicate one."
https://developers.google.com/search/docs/appearance/title-link?visit_id=638302770161667479-4233470687&rd=1
=> CPREL-711: Remove default metadata description because it causes errors in Semrush

packages/dotcom-ui-header/src/__test__/components/__snapshots__/MainHeader.spec.tsx.snap, packages/dotcom-ui-header/src/components/sticky/partials.tsx, packages/dotcom-ui-header/src/components/top/partials.tsx, packages/dotcom-ui-header/src/index.tsx
In this PR I have fixed the myft and Logo links as they were not linked to the navigation props (myFt link is linked to the accounts myFt link, and the logo is linked to the editions.current.url)
=> fix: link myFt & FT logo to navigation Options

packages/dotcom-ui-header/browser.js, packages/dotcom-ui-header/src/enhanced-search/customList.js, packages/dotcom-ui-header/src/enhanced-search/enhancedSearch.js, packages/dotcom-ui-header/src/enhanced-search/styles.scss
In this PR I have addressed some of the latest QA findings [here](https://financialtimes.enterprise.slack.com/files/U04B8H5442F/F05TE3GJNDT/21_sep_enhanced_search_qa_session.pdf?origin_team=T025C95MN&origin_channel=Vall_threads)
1. "Tip text shouldn’t be bold, the text after “Search tip: ...”, as per designs"
2. "Error message should read “failed to load topics and securities results” (The styles will be applied normally in other repos)"
3. "Topics column is still taking up space when empty"
4. "Can we add tracking to errors?" (Firing a custom event 'flyout-load-topics-error') when error happens
5. "Don’t show search bar on sticky header" I have set the aria-hidden property to "true" for sticky header to hide it
=> fix: address latest QA findings

packages/dotcom-ui-header/package.json, packages/dotcom-ui-header/styles.scss, packages/dotcom-ui-layout/package.json
In this PR I have added o-loading, o-message to the styles and peer-dependencies so we don't have to add it to all the other repos
=> include o-loading, o-message into styles

packages/dotcom-ui-header/package.json
This PR updates the n-topic-search package to v6.1.0.
4.0.0 to 6.0.0 only updates n-topic-search's node version to 18, and updates n-express to 27.4.0.
6.1.0 makes a slight improvement to the search dropdown component, to prevent unnecessary requests to the API that provides the topics and securities data.
[See the commit log between 4.0.0 and 6.1.0 for more information](https://github.com/Financial-Times/n-topic-search/compare/v4.0.0...v6.1.0).
=> Update n topic search key event fix

package-lock.json, packages/dotcom-ui-base-styles/package.json, packages/dotcom-ui-header/package.json, packages/dotcom-ui-layout/package.json
A small PR to update to n-ui-foundations-v10.
This allows this module to be used with either v9 or v10 of this library.
=> Support n-ui-foundations v10

packages/dotcom-build-base/package.json, packages/dotcom-build-code-splitting/package.json, packages/dotcom-build-images/package.json, packages/dotcom-build-js/package.json, packages/dotcom-build-sass/package.json, packages/dotcom-middleware-app-context/package.json, packages/dotcom-middleware-app-context/tsconfig.json, packages/dotcom-middleware-asset-loader/package.json, packages/dotcom-middleware-asset-loader/tsconfig.json, packages/dotcom-middleware-navigation/package.json, packages/dotcom-middleware-navigation/tsconfig.json, packages/dotcom-server-app-context/package.json, packages/dotcom-server-asset-loader/package.json, packages/dotcom-server-handlebars/package.json, packages/dotcom-server-navigation/package.json, packages/dotcom-server-react-jsx/package.json, packages/dotcom-ui-app-context/package.json, packages/dotcom-ui-base-styles/package.json, packages/dotcom-ui-bootstrap/package.json, packages/dotcom-ui-data-embed/package.json, packages/dotcom-ui-flags/package.json, packages/dotcom-ui-footer/package.json, packages/dotcom-ui-header/package.json, packages/dotcom-ui-layout/package.json, packages/dotcom-ui-polyfill-service/package.json, packages/dotcom-ui-shell/package.json
The `types` field in `package.json` is meant to reference the declaration files that are generated by TypeScript and then can be consumed by it when installing published packages. Instead of pointing to the declaration files, we were instead pointing to the original TypeScript source code which we are (inappropriately) also publishing. This has the effect that the source code will be transpiled again by TypeScript apps that depend on the Page Kit packages, causing [issues](https://github.com/Financial-Times/dotcom-page-kit/pull/1015) when the `tsconfig.json` is different to ours.
I've updated all the packages to point to the compiled `dist/node/index.d.ts` declaration file, except `dotcom-types-navigation`, which already correctly referenced its single declaration file. I've also …
=> CPP-1802 Correctly point to declaration files instead of TypeScript source

package-lock.json, packages/dotcom-build-code-splitting/package.json
_**Theres no big urgency to this so it can wait until the new year if we think theres any risk to it**_
These peer dependencies were added in https://github.com/Financial-Times/dotcom-page-kit/pull/1012
However I don't believe they are needed as peer dependencies at all as the code splitting package doesn't use them.
It only references them so if they are used in a consuming app the code can be split into their own bundle as they are commonly used.
The issue with including these as a peer dependencies is that it forces apps to include these dependencies at a set version regardless, therefore potentially increasing the work to upgrade an app to the latest page-kit version
Maybe I am missing something here about needing to ensure the bundle we create is based on a certain version? but I …
=> fix: Remove unnecessary peer dependencies for code splitting

packages/dotcom-ui-header/src/__stories__/story.tsx, packages/dotcom-ui-header/src/components/navigation/partials.tsx, packages/dotcom-ui-header/src/components/top/partials.tsx, packages/dotcom-ui-header/src/header.scss, packages/dotcom-ui-header/src/interfaces.d.ts
The Retention team aim to run an AB test with the hope of improving the confusion regarding entry points to myFT and Settings & Account.
The changes include
1. Swapping the position of myFT and Settings & Account entry points, so Setting & Account is at the top and MyFT is below
2. Changing the name of "Settings & Account" to "My Account"
3. Adding a "user" icon next to the My Account and Sign in links
4. Adding "Feed" to the myFT link
These changes are related to user research that discovered
1. Users think the myFT logo is just branding and not a link
2. Settings and Account was not obvious place to go as the main hub for your Account
3. My Account was a more common term for that hub
4. The user icon help to distinguish this as your space
These changes have also been couples with other …
=> Account and myFT entry points test

package-lock.json, packages/dotcom-build-code-splitting/package.json
This peer dependencies were added in https://github.com/Financial-Times/dotcom-page-kit/pull/1012
However I don't believe they are needed as peer dependencies at all as the code splitting package doesn't use them.
It only references them so if they are used in a consuming app the code can be split into their own bundle as they are commonly used.
The issue with including these as a peer dependencies is that it forces apps to include these dependencies at a set version regardless.
**Note:** I think I missed this in my previous dependency clean up (https://github.com/Financial-Times/dotcom-page-kit/pull/1018) because I was looking at `@financial-times` org dependencies
=> fix: Remove unnecessary peer dependencies (n-topic-search) for code splitting

packages/dotcom-server-app-context/schema.md, packages/dotcom-server-app-context/src/__test__/__fixtures__/contextData.ts, packages/dotcom-server-app-context/src/schema.json
loosens the schema for `appContext.contentType` to accept any string. this allows us to use both the current (CAPI-style, PascalCase) values and the old (ES-style, kebab-case) values, and prevents implicitly coupling this schema to the list of possible content types that CAPI can return.
i don't like that the schema validator can throw an error if the app context is invalid, when some of it is provided by data we don't control. but i'm not about to rewrite how this works 😅
=> CPP-1757: loosen appContext.contentType schema

CODEOWNERS, packages/dotcom-build-sass/README.md, packages/dotcom-build-sass/src/index.ts, packages/dotcom-build-sass/src/monitored-sass-loader.ts
Let's build a case to invest in our Sass and its tooling. Or, better, to [proactively move away from sass](https://docs.google.com/document/d/1RuGduWdX0zGsgsp9C7lIhXgqEia6sWK900_3XVwYDIM/edit#heading=h.1f3yolavobef)!
Completed todo:
1. Do the Platforms team think this is a good idea? 💚 
2. Option to turn off 🟢 
3. [Helpful link](https://github.com/Financial-Times/origami/pull/1407) on why this is here, and what we'll do about it 🟢 – will release when this is approved
4. Capture [number of sass compilation errors](https://github.com/webpack-contrib/sass-loader/blob/03773152760434a2dd845008c504a09c0eb3fd91/src/index.js#L68) 🟠  – this is a big enough PR, we can add this later if we want
5. Remote, aggregate monitoring through [biz-ops metrics …
=> Add sass build time monitoring [OR-483]

examples/ft-ui/__test__/integration.test.js, packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap, packages/dotcom-ui-shell/src/components/Shell.tsx
[#inc-2575-polyfill-io-is-intermittently-failing](https://financialtimes.enterprise.slack.com/archives/C06LT31R3BM)
[#polyfill-discussion-2024](https://financialtimes.enterprise.slack.com/archives/C06LNUG3C12)
although this should probably be a major change, we'll release it as a minor to make the upgrade path easier. also tbh nothing really needs polyfills any more?
there is some cleanup work to do after this to remove the `dotcom-ui-polyfill-service` package (going with the quickest fix for now)
=> fix:  don't load polyfill.io in shell

__fixtures__/menus.json, examples/ft-ui/__test__/anonymous-user.test.js, examples/ft-ui/__test__/logged-in-user.test.js, examples/ft-ui/__test__/subscribed-user.test.js, examples/kitchen-sink/__test__/integration.test.js, packages/dotcom-server-navigation/src/__test__/selectMenuDataForEdition.spec.ts, packages/dotcom-server-navigation/src/selectMenuDataForEdition.ts, packages/dotcom-types-navigation/index.d.ts, packages/dotcom-ui-footer/src/__stories__/story-data.ts, packages/dotcom-ui-header/src/__stories__/story-data/index.ts, packages/dotcom-ui-header/src/__stories__/story-data/navbarRight.ts, packages/dotcom-ui-header/src/__stories__/story-data/navbarTopRight.ts, packages/dotcom-ui-header/src/__stories__/story-data/navbarTopRightAnon.ts, packages/dotcom-ui-header/src/__stories__/story-data/profile.ts, packages/dotcom-ui-header/src/__stories__/story.tsx, packages/dotcom-ui-header/src/__test__/components/__snapshots__/MainHeader.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/output/component.spec.tsx, packages/dotcom-ui-header/src/components/navigation/partials.tsx, packages/dotcom-ui-header/src/components/top/partials.tsx, packages/dotcom-ui-header/src/interfaces.d.ts
Roll out the variant of the `experimentalAccountEntryTest` AB test as the default permanent behaviour
In early 2024 the Retention team ran an AB test to try and improve the user experience of the header by trying to reduce confusion of the difference between Settings & Account and myFT. This test was successful so we are now rolling these changes out to all users. The changes that are relevant to this PR are
1. Rename `Settings & Account` to `My Account`
2. Rename `myFT` to `myFT Feed`
3. Move My Account to the top right slot, replacing the myFT logo
4. Move myFT to the bottom right slot, replacing the old Settings & Account link
**Anonymous user - Previous layout**
**Anonymous user - New layout**  
**Signed in user - Previous layout**
**Signed in user - New layout**
1. This relates to …
=> My Account & myFT entry points rollout

examples/kitchen-sink/client/main.js, examples/kitchen-sink/server/controllers/home.js
[Jira Ticket](https://financialtimes.atlassian.net/jira/software/c/projects/ADSDEV/boards/803?selectedIssue=ADSDEV-1856)
As we are no longer using SmartMatch as a product, the endpoint that populates `smartmatch.creative.matches` is being decommissioned by Smartology. 
With this in mind, and given the findings from this [Spike Ticket](https://financialtimes.atlassian.net/jira/software/c/projects/ADSDEV/boards/803?selectedIssue=ADSDEV-1825) this PR removes all references to SmartMatch from `dotcom-page-kit`. 
This PR removes references to smartmatch in an example. 
=> ADSDEV-1856/Remove-references-to-smartmatch

packages/dotcom-ui-header/src/__test__/components/__snapshots__/Drawer.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/components/__snapshots__/MainHeader.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/components/__snapshots__/StickyHeader.spec.tsx.snap, packages/dotcom-ui-header/src/components/ask-ft/askFtButton.tsx, packages/dotcom-ui-header/src/components/drawer/topLevelPartials.tsx, packages/dotcom-ui-header/src/components/sticky/partials.tsx, packages/dotcom-ui-header/src/components/top/partials.tsx
Add `id` attribute to the `Ask FT` buttons on the `header`, `drawer` and the `sticky header`. 
Having unique id was requested for the purpose of targeting the buttons from within Bloomreach.
Ticket: https://financialtimes.atlassian.net/browse/ARP-156
=> Add id attribute to the Ask FT buttons

package-lock.json, packages/dotcom-ui-header/package.json, packages/dotcom-ui-header/src/__test__/components/__snapshots__/MainHeader.spec.tsx.snap, packages/dotcom-ui-header/src/components/top/partials.tsx, packages/dotcom-ui-header/src/header.scss
Use o-header to style the new My Account & Sign in links
These new links were added as part of an AB test. At that stage we hardcoded the styles within this repo but now that the test has proven successful we have moved the styles into o-header
This is a follow up PR to https://github.com/Financial-Times/dotcom-page-kit/pull/1035 which contains additional details about this change and rollout
https://financialtimes.atlassian.net/browse/ACC-3083
=> Update My Account header styles to latest o-header

package-lock.json, packages/dotcom-ui-header/package.json
In v9.5.0 I managed to miss updating the peer dependency for o-header.
This ensure thats the correct version is now being used in v10
=> fix: Update o-header peer dependency

packages/dotcom-ui-header/src/__test__/components/__snapshots__/StickyHeader.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/output/component.spec.tsx, packages/dotcom-ui-header/src/components/sticky/partials.tsx, packages/dotcom-ui-header/src/components/top/partials.tsx, packages/dotcom-ui-header/src/index.tsx, packages/dotcom-ui-header/src/interfaces.d.ts
📢 This is a copy of https://github.com/Financial-Times/dotcom-page-kit/pull/1042 but for v9.x
Replace the myFT logo with the My Account or Sign in links in the sticky header
This change reflects similar changes made to the main header. We now want My Account to be more of a hub that can take you to places like myFT so promoting this from this point in the navigation makes more sense.
https://github.com/Financial-Times/dotcom-page-kit/assets/524573/fc53f0d0-d706-4fff-9c05-e7b16c83ec8d
https://financialtimes.atlassian.net/browse/ACC-3083
=> Replace sticky header myFT link with My Account / Sign in - v9

packages/dotcom-ui-header/src/__test__/components/__snapshots__/StickyHeader.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/output/component.spec.tsx, packages/dotcom-ui-header/src/components/sticky/partials.tsx, packages/dotcom-ui-header/src/components/top/partials.tsx, packages/dotcom-ui-header/src/index.tsx, packages/dotcom-ui-header/src/interfaces.d.ts
Replace the myFT logo with the My Account or Sign in links in the sticky header
This change reflects similar changes made to the main header. We now want My Account to be more of a hub that can take you to places like myFT so promoting this from this point in the navigation makes more sense.
https://github.com/Financial-Times/dotcom-page-kit/assets/524573/fc53f0d0-d706-4fff-9c05-e7b16c83ec8d
https://financialtimes.atlassian.net/browse/ACC-3083
=> Replace sticky header myFT link with My Account / Sign in

package-lock.json, packages/dotcom-build-sass/package.json, packages/dotcom-build-sass/src/index.ts
Resolve .css `@import` from node_modules. This will enable the use of Origami "o3", which moves from Sass to CSS.
=> feat: support .css import from node_modules [OR-726]

examples/ft-ui/__test__/integration.test.js, examples/kitchen-sink/__test__/integration.test.js, package-lock.json, packages/dotcom-ui-header/package.json, packages/dotcom-ui-header/src/__test__/components/__snapshots__/Drawer.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/components/__snapshots__/MainHeader.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/components/__snapshots__/StickyHeader.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/output/drawer.spec.tsx, packages/dotcom-ui-header/src/components/ask-ft/askFtButton.tsx, packages/dotcom-ui-header/src/components/drawer/additionalPartials.tsx, packages/dotcom-ui-header/src/components/drawer/topLevelPartials.tsx, packages/dotcom-ui-header/src/components/search/partials.tsx, packages/dotcom-ui-header/src/header.scss, packages/dotcom-ui-header/styles.scss
As part of search navbar redesign we need to change design and position of ask button, design of edition switcher and position of subscribe button,
Changes from o-header:
- close button moved to left
- simplified design of edition switcher
- size and style of search bar and search button
Figma: 
https://www.figma.com/design/L6qyUFPPLRmf59OxTkz2VJ/Semantic-Search?node-id=10-629&m=dev
o-header changes PR: https://github.com/Financial-Times/origami/pull/1725
https://financialtimes.atlassian.net/browse/CON-3426
Before:
After:
=> CON-3426: design changes ask button, edition switcher, subscribe button

package-lock.json, packages/dotcom-ui-header/package.json, packages/dotcom-ui-header/src/header.scss, packages/dotcom-ui-header/styles.scss
in the new search bar design on header we had the issue with ask to ft button that the style looks incorrect
this PR fixed it
it fix too the problems with typeahead results box
Before:
After:
=> CON-3426: fix padding on ask to ft in header

examples/ft-ui/__test__/logged-in-user.test.js, examples/ft-ui/__test__/subscribed-user.test.js
Update the link text for myFT in the tests
The link text was recently changed in the origami navigation service as these tests use real data these also need updating.
Original navigation service change https://github.com/Financial-Times/origami-navigation-service/pull/976
=> chore: update myft wording in tests

.storybook/.browserslistrc, .storybook/main.js, .storybook/webpack.config.js, examples/kitchen-sink/__test__/build.test.js, package-lock.json, package.json, packages/dotcom-ui-header/browser.js, packages/dotcom-ui-header/package.json, packages/dotcom-ui-header/src/__stories__/story.tsx, packages/dotcom-ui-header/src/__test__/components/TypeaheadIntegration.test.tsx, packages/dotcom-ui-header/src/__test__/components/__snapshots__/Drawer.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/components/__snapshots__/MainHeader.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/components/__snapshots__/StickyHeader.spec.tsx.snap, packages/dotcom-ui-header/src/components/ask-ft/askFtButton.tsx, packages/dotcom-ui-header/src/components/drawer/topLevelPartials.tsx, packages/dotcom-ui-header/src/components/search/partials.tsx, packages/dotcom-ui-header/src/components/sticky/partials.tsx, packages/dotcom-ui-header/src/components/top/partials.tsx, packages/dotcom-ui-header/src/header.scss, packages/dotcom-ui-header/styles.scss
This PR includes changes from https://github.com/Financial-Times/dotcom-page-kit/pull/1051. It has been rebased and merge conflicts has been resolved. These two features has to be released at the same time. Please, see the very first commit https://github.com/Financial-Times/dotcom-page-kit/pull/1052/commits/7f8be8ea084c447db46d503396938ae11521c017
cc: @Ventzy 
1. Mark-up changes to accommodate `o-header` v.14.0.1. (https://github.com/Financial-Times/origami/pull/1777)
1.1 Changing input search field to `type="search"`. This should improve the screen reader experience, also reflect true sematic meaning of the input field.
1.2 Input search field now has [`role="combobox"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/combobox_role) to indicate that an element as an …
=> [CON-3348] o-header and typeahead

__fixtures__/menus.json, packages/dotcom-ui-footer/src/__stories__/footer.ts
We will be decommissioning the page --> https://www.ft.com/tour/community.
We need to remove the links pointing to it.
Part of --> https://financialtimes.atlassian.net/browse/HIVE-2004
=> HIVE-2004-Decommission-Community-tour-page-and-links

packages/dotcom-ui-header/src/__test__/components/__snapshots__/Drawer.spec.tsx.snap, packages/dotcom-ui-header/src/components/drawer/additionalPartials.tsx, packages/dotcom-ui-header/src/components/drawer/topLevelPartials.tsx
Fix Ask FT button padding in the drawer - align with the `o-header` v14.0.2 change moving the Ask FT button into a `div.o-header__drawer-actions` - see https://github.com/Financial-Times/origami/commit/3c222a8de2e0232fe0e2252a5b6480ec7aece255#diff-3442766672b321ac20a66cb73a01b7028a2d9b365f7c4a1f9df0c9ffbf483909
| Before | After |
|--------|--------|
|  ![image](https://github.com/user-attachments/assets/e8052905-73f9-4159-b687-aa9cadfb845d) | ![image](https://github.com/user-attachments/assets/a8664ba7-3b87-4940-a1ed-d331cc590d95) |
=> fix (dotcom-ui-header): fix Ask FT button padding in the drawer

packages/dotcom-ui-header/src/header.scss
Relative position is declared in `o-header` css rule sets. See https://github.com/Financial-Times/origami/pull/1808/files#diff-e174d6ea6859969799730b2996e108172a5897a1e2efc779198a26bc6023afacR3
=> chore: remove obsolete scss declaration

package-lock.json, packages/dotcom-ui-header/package.json
* 14.0.3 The new `o-header` version increases `z-index` for mega nav menu. It should fix issues where content below nav menu was appearing above the nav menu items.
* In addition 14.0.4 fixes an issue with sub items scrolling. https://github.com/Financial-Times/origami/releases/tag/o-header-v14.0.4
=> chore: bump `o-header` version

package-lock.json, packages/dotcom-build-code-splitting/package.json
mistakenly added in #1012. the packages are only mentioned in this plugin as things to bundle when code splitting, they're not actually dependencies of this plugin.
=> backstage: remove extraneous peer dependencies from dotcom-build-code-splitting

package-lock.json, packages/dotcom-ui-header/package.json, packages/dotcom-ui-header/src/header.scss
Recently @fenglish reported that Navigation bar is no longer accessible if user disables JavaScript. This change is caused by recent designs decisions to the search bar container. It started overlaying the content.
| Before | After |
|--------|-------|
| <img width="1342" alt="Screenshot 2024-09-26 at 16 34 53" src="https://github.com/user-attachments/assets/209264c6-99ca-43bb-9911-96ecaf32a3fb"> |  <img width="1340" alt="Screenshot 2024-09-26 at 16 34 14" src="https://github.com/user-attachments/assets/c50d8cb0-d174-4be3-b0bb-2615a22b20c7">
* `n-topic-search` bump adds `data-trackable` attribute to clickable links in typeahead. - https://github.com/Financial-Times/n-topic-search/releases/tag/v8.0.5
=> Change Search Container position for core experience

packages/dotcom-ui-shell/src/__test__/components/GTMHead.test.tsx, packages/dotcom-ui-shell/src/__test__/components/__snapshots__/GTMHead.test.tsx.snap, packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap, packages/dotcom-ui-shell/src/components/GTMHead.tsx
> [!Note]
> This PR supersedes the deleted PR `ADSDEV-2064/proxy-gtm-requests`, reducing its scope to updating the source of the  script tag in the HEAD
This PR enables [First Party mode](https://developers.google.com/tag-platform/tag-manager/first-party/setup-guide?setup=manual) for Google Tag Manager (GTM): when the `ads-first-party-gtm` Toggler flag is enabled the GTM script is loaded from `ft.com/page-resources` rather than `www.googletagmanager.com/gtm.js`
This should offer us some protection against anti-tracking measures that block requests to `googletagmanager.com`
Reviewing commit-by-commit is recommended. The PR comprises 2:
1. The substantive changes
2. Snapshot updates
=> ADSDEV 2064: GTM first party mode

examples/ft-ui/__test__/gtm.test.js, examples/ft-ui/server/controllers/home.jsx, packages/dotcom-ui-shell/src/__test__/components/__snapshots__/GTMHead.test.tsx.snap, packages/dotcom-ui-shell/src/components/GTMHead.tsx
This PR corrects an oversight in #1091, adding a trailing slash to the proxy URL.
The bulk of the change is related to tests that confirm that the feature works as intended
=> ADSDEV 2064: GTM first party mode update

README.md
Noticed the link was broken when trying to access the contribution guides through the README
- Correct the spelling of the contribution guide link in README
=> [Fix] README link to contribution guidelines

packages/dotcom-ui-base-styles/src/lib/fontFaces.ts, packages/dotcom-ui-shell/src/__test__/components/ResourceHints.test.tsx, packages/dotcom-ui-shell/src/__test__/components/__snapshots__/ResourceHints.test.tsx.snap, packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap, packages/dotcom-ui-shell/src/__test__/lib/getResourceType.spec.ts
Updating all Origami Build Service URLs in **dotcom-page-kit** that used `source_code=origami`, to use `source_code=page-kit` instead. This gives a accurate reporting on the source of the build service request.
=> [Update] source_code of Origami Build service URLs

packages/dotcom-ui-header/src/components/navigation/partials.tsx
`aria-hidden="true"` is always applied on the mobile navigation. This means assistive tech users can't navigate to markets data on mobile.
It seems unnecessary as `display: none` is set on desktop.
=> Remove `aria-hidden="true"` from mobile navigation

examples/kitchen-sink/package.json, package-lock.json
Consumes https://github.com/Financial-Times/advertising/pull/373 so that changes to the mvt2 flag are applied.
=> [AG-194] chore: bump oAds to consume mvt2 flag changes

examples/ft-ui/__test__/integration.test.js, examples/ft-ui/package.json, examples/ft-ui/server/app.js, examples/ft-ui/server/controllers/home.jsx, package-lock.json, packages/dotcom-build-base/src/index.ts
the semantics of the `[path]` placeholder changed in [version 5 of the plugin](https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/CHANGELOG.md#600-2020-09-14), which causes `Conflict: Multiple assets emit different content to the same filename .gz` errors with a production build.
also changes the `ft-ui` example to build in production mode, so we've at least got something that's testing that.
=> Fix compression-webpack-plugin filename option

examples/building-sass-files/README.md, examples/building-sass-files/__test__/integration.test.js, examples/building-sass-files/src/main.scss, examples/ft-ui/webpack.config.js, examples/kitchen-sink/webpack.config.js, package-lock.json, packages/dotcom-build-sass/README.md, packages/dotcom-build-sass/package.json, packages/dotcom-build-sass/src/index.ts
With Webpack 5 we've been able to update to a newer version of the `sass-loader` loader. The newer version [no longer](https://github.com/webpack-contrib/sass-loader/releases/tag/v11.0.0) requires imports to be prefixed with a `~` if they want to use Webpack's resolution logic (i.e., traversing `node_modules`.) This is particularly good for stylesheets that import stylesheets that themselves import stylesheets, as the transitive imports are no longer required to use the non-standard `~` prefix to work.
This means we no longer need to use the `postcss-import` plugin to work around the import behaviour. Importing using `sass-loader` makes native use of Webpack's resolution logic so should be better equipped to handle de-duping etc., though that has not been thoroughly tested: the main …
=> CPP-2222 Use Webpack's native import resolution for S/CSS and drop Postcss

package-lock.json, packages/dotcom-build-css/README.md, packages/dotcom-build-css/package.json, packages/dotcom-build-css/src/index.ts, packages/dotcom-build-css/tsconfig.json, packages/dotcom-build-sass/README.md, packages/dotcom-build-sass/package.json, packages/dotcom-build-sass/src/index.ts, packages/dotcom-build-sass/tsconfig.json, tsconfig.build.json
We used to have a plugin with the same name, but that was deprecated as there was not much demand for it. Now that Origami is moving towards a native CSS approach, and it encouraging others to do the same, it makes sense to bring this plugin back.
Much of the code is shared between the Sass and CSS plugins, as once the Sass is compiled to CSS we want to do the same set of transformations to both.
=> CPP-2223 Add plugin to build native CSS

packages/dotcom-ui-base-styles/sass/_mixins.scss, packages/dotcom-ui-base-styles/sass/grid/_mixins.scss, packages/dotcom-ui-base-styles/sass/grid/main.scss, packages/dotcom-ui-base-styles/sass/main.scss, packages/dotcom-ui-base-styles/sass/typography/main.scss, packages/dotcom-ui-base-styles/sass/util/README.md, packages/dotcom-ui-base-styles/sass/util/_mixins.scss, packages/dotcom-ui-base-styles/sass/util/main.scss
this PR moves all the sass from [n-ui-foundations](https://github.com/Financial-Times/n-ui-foundations/) into `dotcom-ui-base-styles`. since this includes all the git history from n-ui-foundations, there's a lot of commits, and it's not going to be easily reviewable on its own. i'm going to do the actual work of integrating this sass into `dotcom-ui-base-styles` in a separate PR based on this one, to make that easier to review.
=> merge n-ui-foundations into dotcom-ui-base-styles

packages/dotcom-ui-base-styles/package.json
The new `sass` directory was not added to the `files` filter in the `package.json` so wasn't being included in npm releases.
=> Include ex-n-ui-foundations Sass files in dotcom-ui-base-styles' npm package

package-lock.json, packages/dotcom-build-sass/README.md, packages/dotcom-build-sass/src/index.ts
We don't install the `sass` package by default, only `sass-embedded`, so it makes sense to default to the latter.
=> Default to sass-embedded implementation in Sass plugin

packages/dotcom-ui-bootstrap/README.md, packages/dotcom-ui-bootstrap/lib/bootstrap.js, packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap
https://financialtimes.enterprise.slack.com/archives/C08CDEJCVCN
=> fix: don't revert to core experience on error from third-party script

package-lock.json, packages/dotcom-ui-base-styles/package.json
required for o3 migration to avoid peer dependency conflicts in `n-topic-search` (which is a dependency of Page Kit, but also depends on Page Kit for demos)
=> fix: update to o3-foundation v3

packages/dotcom-ui-header/src/__test__/components/__snapshots__/DropdownNavigation.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/components/__snapshots__/MainHeader.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/components/__snapshots__/StickyHeader.spec.tsx.snap, packages/dotcom-ui-header/src/components/dropdown-navigation/dropdownNavigation.js, packages/dotcom-ui-header/src/components/dropdown-navigation/dropdownNavigation.tsx
Jira: [ENT-2257](https://financialtimes.atlassian.net/browse/ENT-2257)
- A quick fix for the dropdown fetch functionality to include the session with the fetch request.
- Removed error logging.
- Additional cosmetic clean-up.
- Fixing an issue with a missing sticky header if the header varian is 'logo-only'
[ENT-2257]: https://financialtimes.atlassian.net/browse/ENT-2257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Include credentials in dropdown fetch

packages/dotcom-ui-header/README.md, packages/dotcom-ui-header/src/__test__/components/MainHeader.spec.tsx, packages/dotcom-ui-header/src/__test__/components/__snapshots__/MainHeader.spec.tsx.snap, packages/dotcom-ui-header/src/components/dropdown-navigation/dropdownNavigation.js, packages/dotcom-ui-header/src/components/dropdown-navigation/dropdownNavigation.scss, packages/dotcom-ui-header/src/components/top/partials.tsx, packages/dotcom-ui-header/src/interfaces.d.ts, packages/dotcom-ui-layout/README.md, packages/dotcom-ui-layout/src/components/Layout.tsx
This PR resolves an issue with pro navigation (pro dropdown), where after using a link to go to a page and coming back to the last page would result in the dropdown visibly flashing for a second, as well as on some pages resulting in the first click on the dropdown button after returning to the page leading to the dropdown opening and immediately closing. 
This issue has now been resolved and when a user clicks on a link we ensure that we would close the dropdown before we redirect to the new page.
Additionally this PR removes the exposure event added last time, since after speaking with Emilio who conversed with Amplitude it was found we would not need it, as an Amplitude setup with page:view-s can be used instead.
Please read the [contributing …
=> Fix pro navigation flashing behavior when moving back after redirect

packages/dotcom-ui-shell/src/__test__/components/__snapshots__/DocumentHead.test.tsx.snap, packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap, packages/dotcom-ui-shell/src/components/DocumentHead.tsx
`rel="alternate icon"` isn't a thing (looks to have been conflated with `rel="alternate stylesheet"`). with multiple `rel="icon"` tags [browsers prioritise them](https://html.spec.whatwg.org/multipage/links.html#rel-icon) based on what `type` they can render and what `sizes` they want.
=> fix: use rel="icon" instead of rel="alternate icon" for PNG fallbacks

package-lock.json, packages/dotcom-ui-header/package.json, packages/dotcom-ui-header/src/__test__/components/__snapshots__/Drawer.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/components/__snapshots__/MainHeader.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/components/__snapshots__/StickyHeader.spec.tsx.snap, packages/dotcom-ui-header/src/components/ask-ft/askFtButton.scss, packages/dotcom-ui-header/src/components/ask-ft/askFtButton.tsx, packages/dotcom-ui-header/src/header.scss
We want to align the Ask FT button in the header with professional styles, and for this, we’d like to use the o3-button package to render it as an o3 link button.
JIRA ticket: [ELES-1863](https://financialtimes.atlassian.net/jira/software/c/projects/ELES/boards/1628?selectedIssue=ELES-1863)
- Previously, the Ask FT button relied on the `o-header__ask-ft-button` class to inherit styles from the `@financial-times/o-header` package.
- The initial goal was to use the `o3-button` package to render the button as an o3 link button for improved consistency with professional themes on both `@financial-times/o-header` and `dotcom-ui-header` packages.
- After discussion with the Origami team ([see related PR](https://github.com/Financial-Times/origami/pull/2174) and …
=> ELES-1863 Update Ask FT button on the header

packages/dotcom-ui-shell/src/__test__/components/__snapshots__/DocumentHead.test.tsx.snap, packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap, packages/dotcom-ui-shell/src/lib/imageServiceIconURL.ts
[CPP-2537](https://financialtimes.atlassian.net/browse/CPP-2537)
This PR updates favicon and icons references from using image service v2 to v3.
- Updated the serviceURL in the Image Service Builder to use v3 endpoint
- Updated the source to use [biz op system code ](https://biz-ops.in.ft.com/System/page-kit)
- Made snapshot updates to reflect these changes
[CPP-2537]: https://financialtimes.atlassian.net/browse/CPP-2537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CPP-2537 feat: migrate favicon and icons to use image sevice v3

packages/dotcom-server-handlebars/src/__test__/helpers.spec.ts, packages/dotcom-server-handlebars/src/helpers/README.md, packages/dotcom-server-handlebars/src/helpers/resize.ts
[CPP-2604](https://financialtimes.atlassian.net/browse/CPP-2604)
As part of the image service v3 migration, this PR updates the resize function to handle image service v2 URLs, taking in the new v3 URL. 
It also updates the relevant tests. 
[CPP-2604]: https://financialtimes.atlassian.net/browse/CPP-2604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CPP-2604 feat: update resize function to image service v3 & tests

packages/dotcom-ui-header/src/__test__/components/__snapshots__/MainHeader.spec.tsx.snap, packages/dotcom-ui-header/src/__test__/components/__snapshots__/StickyHeader.spec.tsx.snap, packages/dotcom-ui-header/src/components/top/partials.tsx
This PR add origami class to the cta button to be small instead of the default button and also add css class to hide the cta on mobile. This should only show on desktop devices.
[Jira Ticket](https://financialtimes.atlassian.net/browse/LIF-664)
=> LIF-664: Fix restart sub button size
