Financial-Times/dotcom-page-kit

- packages/dotcom-server-app-context/schema.md
- packages/dotcom-server-app-context/src/schema.json
one more from article smoke test whack-a-mole
> add live-blog as a valid content type

- packages/dotcom-ui-header/src/components/top/partials.tsx
> Use SVG header for TopColumnCenterNoLink

- packages/dotcom-ui-shell/src/__test__/components/__snapshots__/DocumentHead.test.tsx.snap
- packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap
- packages/dotcom-ui-shell/src/components/DocumentHead.tsx
- packages/dotcom-ui-shell/src/lib/imageServiceIconURL.ts
png is 813 bytes and svg is 450 bytes (because we can gzip it)
> use an svg icon and fallback to png

- .circleci/config.yml
- package.json
We need teams to migrate their CircleCI pipelines
> Add npm-publish-token CircleCI context 

- .circleci/config.yml
> Only run the CircleCI deploy job once

- packages/dotcom-ui-header/src/enhanced-search/customList.js
- packages/dotcom-ui-header/src/enhanced-search/enhancedSearch.js
In this PR, I have trimmed the search sentnece when it is so long > 60 char and dynamically set the form.action according to the **enhancedSearchUrl**
> backtrack: update form action and trim text

- packages/dotcom-ui-header/src/enhanced-search/customList.js
- packages/dotcom-ui-header/src/enhanced-search/enhancedSearch.js
In this PR I have updated wording in the flyout to match the designs mentioned in the ticket 
[JIRA ELES-794)](https://financialtimes.atlassian.net/browse/ELES-794)
Desings
[Flyout typing prompt](https://www.figma.com/file/Hjz28uiQqs8pxUm6X7fCG5/FT.com_Search_Test?type=design&node-id=153-6533&mode=design&t=rLW08eQlkduo7XPI-4) (focus state before typing)
[Flyout typing prompt](https://www.figma.com/file/Hjz28uiQqs8pxUm6X7fCG5/FT.com_Search_Test?type=design&node-id=153-6590&mode=design&t=rLW08eQlkduo7XPI-4) (started typing)
> Eles 794 remove reference to enhanced from UI designs

- packages/dotcom-ui-header/browser.js
- packages/dotcom-ui-header/package.json
- packages/dotcom-ui-header/src/enhanced-search/customList.js
- packages/dotcom-ui-header/src/enhanced-search/enhancedSearch.js
- packages/dotcom-ui-header/src/enhanced-search/styles.scss
In This PR I have,
-  Added option to show the search-bar by default (searchState) to help with the enhanced-search test, 
- Fixed a UI bug by removing the extra top 16px padding
- Added null checks to the createHtml method in the CustomList class
> Eles 701 show search bar by default on homepage based on ammit flag

- packages/dotcom-ui-header/src/enhanced-search/enhancedSearch.js
- packages/dotcom-ui-header/src/enhanced-search/styles.scss
This PR is to fix 
1. The search url for sticky and drawer search bars
2. hide the desktop search bars on small screens
3. fix the width of the flyout for drawer search
> Fix search url

- packages/dotcom-ui-header/src/enhanced-search/customList.js
- packages/dotcom-ui-header/src/enhanced-search/enhancedSearch.js
In this PR I have fixed minor ui bugs
- show loading spinner for exactly minLength (2 in by default)
- replace className with class in html to correctly style the error message
> Fix minor UI bugs

- examples/express-with-jsx/views/Layout.jsx
- packages/dotcom-server-handlebars/src/helpers/slice.ts
- packages/dotcom-ui-footer/src/components/partials.tsx
- packages/dotcom-ui-shell/src/__test__/components/__snapshots__/DocumentHead.test.tsx.snap
- packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap
- packages/dotcom-ui-shell/src/components/DocumentHead.tsx
This PR is to sync recent changes done to dotcom-page-kit main into enhanced-search brahc
> Sync with main

- packages/dotcom-build-sass/src/monitored-sass-loader.ts
We were monitoring each Sass entry point's build time. They run in parallel which means we were inflating the total time Sass takes to build.
> Monitor sass build time per webpack run, across async builds.

- examples/ft-ui/__test__/integration.test.js
- packages/dotcom-ui-shell/src/__test__/components/__snapshots__/Shell.test.tsx.snap
- packages/dotcom-ui-shell/src/components/Shell.tsx
> Polyfill backport

- package-lock.json
- packages/dotcom-ui-header/package.json
Update o-header dependency to decrease the width of the search bar
https://financialtimes.atlassian.net/browse/CON-3426
> CON-3426: update o-header dependency

- package-lock.json
- packages/dotcom-ui-header/package.json
we need to bum n-topic-search dependency to solve some small css design bugs
https://financialtimes.atlassian.net/browse/CON-3544
> bump n-topic-search dependency

- packages/dotcom-build-code-splitting/src/index.ts
https://financialtimes.slack.com/archives/C3TJ6KXEU/p1740132488335589
> fix: only set name to vendors for defaultVendors chunk

- __fixtures__/menus.json
- packages/dotcom-ui-footer/src/__test__/fixtures/footer.ts
- packages/dotcom-ui-header/src/__test__/components/__snapshots__/Drawer.spec.tsx.snap
- packages/dotcom-ui-header/src/__test__/fixtures/drawerUK.ts
https://financialtimes.atlassian.net/browse/HIVE-2176
> HIVE-2176-changing-forums-and-bpd-links

- package-lock.json
- packages/dotcom-ui-header/package.json
Bumps n-topic-search to fix issue discovered during [next-home-page migration](https://github.com/Financial-Times/next-home-page/pull/1704#issuecomment-2804617400).
> bump n-topic-search

- packages/dotcom-ui-header/src/__test__/components/__snapshots__/DropdownNavigation.spec.tsx.snap
- packages/dotcom-ui-header/src/__test__/components/__snapshots__/MainHeader.spec.tsx.snap
- packages/dotcom-ui-header/src/__test__/components/__snapshots__/StickyHeader.spec.tsx.snap
- packages/dotcom-ui-header/src/components/dropdown-navigation/constants.ts
Jira: [ENT-2315](https://financialtimes.atlassian.net/browse/ENT-2315)
Change ‘Feed’ to ‘myFT feed’ 
[ENT-2315]: https://financialtimes.atlassian.net/browse/ENT-2315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Dropdown feed link change copy

- package-lock.json
- packages/dotcom-ui-header/package.json
Bumps [n-topic-search to v10.0.2](https://github.com/Financial-Times/n-topic-search/releases/tag/v10.0.2)
> chore: bump n-topic-search

- packages/dotcom-ui-layout/styles.scss
This PR updates the header background colour to match the unified ad designs available here https://www.figma.com/design/54JMLdwlaW8IZfWLyo2apw/AG-2352--Audit-ad-slot-styling-across-FT.com-and-app?node-id=6174-39&p=f&t=lrEjP6agadAnlF5H-0
> feat: change header background colour

- package-lock.json
- packages/dotcom-ui-footer/package.json
includes this fix: https://github.com/Financial-Times/origami/pull/2221
> CPP-2630: update o-footer in dotcom-ui-footer
